lesson3 has been done
NataliaStekolnikova/Homework pull request #1
Opened 2023-05-31 19:34 UTC by NataliaStekolnikova

lesson3 has been done

2023-06-18 16:07 UTC, a-kosak-mbx requested changes

2023-06-18 16:07 UTC, a-kosak-mbx commented on lesson3.py
> +print("Самое длинное слово в предложении: ", longest_word)
Можно и так, но лучше использовать `max` в сочетании с `key=len`.

2023-06-18 16:07 UTC, a-kosak-mbx commented on lesson3.py
> +words = re.findall(r'\b\w+\b', sentence)  # Разбиваем предложение на слова с помощью регулярного выражения
Регулярное выражение не будет работать для слов, в которых есть дефис.

2023-06-18 16:07 UTC, a-kosak-mbx commented on lesson3.py
> +    if char not in unique_chars:
Плохо. Я уже не раз говорил об этом. Если хотите использовать коллекцию, в которую добавляете встреченные символы, то используйте что-то более производительное. Поиск по списку имеет линейную сложность. Зачем это нужно?

2023-06-18 16:07 UTC, a-kosak-mbx commented on lesson3.py
> +        elif char.isupper():
Зачем проверять на upper? Очевидно, что после всех ваших проверок, если не lower, то upper. Переделайте.

2023-07-04 18:40 UTC, NataliaStekolnikova commented on lesson3.py
> +        elif char.isupper():
исправлено

2023-07-04 18:41 UTC, NataliaStekolnikova commented on lesson3.py
> +    if char not in unique_chars:
исправлено

2023-07-04 18:41 UTC, NataliaStekolnikova commented on lesson3.py
> +words = re.findall(r'\b\w+\b', sentence)  # Разбиваем предложение на слова с помощью регулярного выражения
исправлено

2023-07-04 18:41 UTC, NataliaStekolnikova commented on lesson3.py
> +print("Самое длинное слово в предложении: ", longest_word)
ОК

2023-07-05 12:35 UTC, a-kosak-mbx requested changes
Не понимаю, что вы сделали. Половина кода пропала. В конце файла какое-то непонятное слово git. Переделывайте нормально.

2023-07-05 13:16 UTC, a-kosak-mbx requested changes

2023-07-05 13:16 UTC, a-kosak-mbx commented on lesson3.py
> +uppercase_count = uppercase_count - lowercase_count
Вышло как-то странно Что мешает просто использовать `else: uppercase_count += 1`?

2023-07-05 13:16 UTC, a-kosak-mbx commented on lesson3.py
> +print("Результат:", ''.join(unique_chars))
Решение не соответствует условию.

2023-07-05 13:16 UTC, a-kosak-mbx commented on lesson3.py
> +git
Этого точно не должно быть.

2023-07-16 13:33 UTC, a-kosak-mbx approved these changes
Если хотите, можете исправить мелочи. А можете сразу подлить.

2023-07-16 13:33 UTC, a-kosak-mbx commented on lesson3.py
> +# gigЗадачи для закрепления на занятии
Вы совсем не смотрите, что отсылаете на проверку? Что это за gig появился? Уже второй раз, хотя на этот ни на что не влияет, поскольку в комментариях находится.

2023-07-16 13:33 UTC, a-kosak-mbx commented on lesson3.py
> +            uppercase_count += 1
Почему не просто `elif`?

2023-07-19 18:43 UTC, merged