Lesson6 has been done
NataliaStekolnikova/Homework pull request #4
Opened 2023-07-12 19:22 UTC by NataliaStekolnikova

Lesson6 has been done

2023-07-16 11:00 UTC, a-kosak-mbx requested changes
Удалите отсюда lesson3 и lesson5. И за их наличие сразу минус балл.
Может быть хотя бы это как-то мотивирует вас проверять то, что вы делаете.

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +        print(num)
У вас два почти одинаковых цикла. Вынесите их за if, а в if задайте направление счета в какой-нибудь переменной.

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +digit_count = 0
Зачем вам этот digit_count?

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +original_num = num
Сделайте в одну строчку.

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +    reversed_num = reversed_num * 10 + last_digit
Сделайте в одну строчку.

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +    digit_count += 1
Зачем?

2023-07-16 11:00 UTC, a-kosak-mbx commented on lesson6.py
> +    elif num % 5 == 0:
В худшем случае вы делаете 4 деления. Зачем? Почему бы не ограничиться всего двумя?

2023-07-19 15:12 UTC, NataliaStekolnikova commented
> Удалите отсюда lesson3 и lesson5. И за их наличие сразу минус балл. Может быть хотя бы это как-то мотивирует вас проверять то, что вы делаете.

removed

2023-07-19 15:13 UTC, NataliaStekolnikova commented on lesson6.py
> +    elif num % 5 == 0:
fixed

2023-07-19 15:13 UTC, NataliaStekolnikova commented on lesson6.py
> +    digit_count += 1
thank you for notes, agree, fixed

2023-07-19 15:13 UTC, NataliaStekolnikova commented on lesson6.py
> +    reversed_num = reversed_num * 10 + last_digit
OK, fixed

2023-07-19 15:22 UTC, NataliaStekolnikova commented on lesson6.py
> +original_num = num
fixed

2023-09-03 09:30 UTC, a-kosak-mbx approved these changes

2023-09-09 09:38 UTC, a-kosak-mbx approved these changes

2023-09-30 16:17 UTC, merged